apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-portal
  namespace: student-portal
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: sre-lab
spec:
  ingressClassName: alb
  rules:
    - host: student-portal.${LAB_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-portal-frontend
                port:
                  number: 80
