apiVersion: v1
kind: ConfigMap
metadata:
  name: student-portal-backend-config
  namespace: student-portal
data:
  PORT: "4000"
  DD_ENV: "lab"
  DD_SERVICE: "student-portal-backend"
  DD_VERSION: "1.0.0"
