apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: ecommerce
  labels:
    app: ecommerce-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
        tags.datadoghq.com/env: "lab"
        tags.datadoghq.com/service: "ecommerce-frontend"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        ad.datadoghq.com/ecommerce-frontend.logs: '[{"source":"nginx","service":"ecommerce-frontend"}]'
    spec:
      containers:
        - name: ecommerce-frontend
          image: ${ECR_REGISTRY}/sre-lab/ecommerce-frontend:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
