apiVersion: v1
kind: Service
metadata:
  name: support-tickets-frontend
  namespace: support-tickets
spec:
  selector:
    app: support-tickets-frontend
  ports:
    - port: 80
      targetPort: 8080
