apiVersion: v1
kind: ConfigMap
metadata:
  name: food-delivery-backend-config
  namespace: food-delivery
data:
  PORT: "4000"
  DD_ENV: "lab"
  DD_SERVICE: "food-delivery-backend"
  DD_VERSION: "1.0.0"
  REDIS_HOST: "food-delivery-redis"
  REDIS_PORT: "6379"
